### ISSUE TITLE
Методы для взаимодействия с БД расположены в сущностях

### ISSUE THREAD

**Issue by Pawnhouse** [unext2/practice#1]
В сущностях не должно быть методов для их сохранения, изменения и т.д. Для этого нужно создать DAO.

https://github.com/unext2/practice/blob/f3e142dd66fbb683071615062161192d19e5459b/2.JDBC/src/main/java/com/database/Albums.java#L61

**Comment by unext2** [comment]
В 3 задании реализовано всё согласно правилам!
