### ISSUE TITLE
Добавить URL бэкенда в переменную окружения

### ISSUE THREAD

**Issue by Pawnhouse** [unext2/practice#7]
https://github.com/unext2/practice/blob/8f823a4cc57df9020da27f0f05d9460ff0888c92/4.Angular/src/app/service/album.service.ts#L10

https://github.com/unext2/practice/blob/8f823a4cc57df9020da27f0f05d9460ff0888c92/5.React/src/services/AlbumService.js#L3

`"http://localhost:8080/api"` в Angular и React

https://habr.com/ru/articles/477214/

https://create-react-app.dev/docs/adding-custom-environment-variables/

https://vitejs.dev/config/#using-environment-variables-in-config

**Comment by unext2** [comment]
Исправил
